User balance lookup
nina-protocol/nina pull request #1048
Opened 2023-05-10 19:25 UTC by ikjudd

- Closes #1047

2023-05-10 19:39 UTC, ikjudd commented
- [ ] Displays Bundlr balance to user in`<Balance />`
- [ ] Displays correct Bundlr balance of another user in `<Balance />` if user's `publicKey` is found in `onboardingWhitelist`
- [ ] Displays user balances in `<Balance />` if user's `publicKey` is found in `onboardingWhitelist`

2023-05-10 19:47 UTC, ejf89 requested changes
This shows the connected wallets USDC, Sol, and Available to collect. Only the Bundlr balance is being set for the Profile being viewed.

Please update accordingly

2023-05-11 19:48 UTC, ejf89 approved these changes

2023-05-11 21:23 UTC, ejf89 approved these changes

2023-05-11 21:28 UTC, merged