Searchnav
nina-protocol/nina pull request #424
Opened 2022-10-17 15:55 UTC by ikjudd

2022-10-17 21:02 UTC, ejf89 commented on js/web/components/Hub.js
> +import Head from 'next/head'
remove unused import plz

2022-10-17 21:12 UTC, ejf89 commented on js/web/components/NavSearch.js
> +    const response = await axios.post(
lets add the SDK functon for this

2022-10-17 21:18 UTC, ejf89 commented on js/web/components/Release.js
> +  console.log(releaseState)
remove logs plx

2022-10-17 21:18 UTC, ejf89 commented on js/web/components/ReleasePurchase.js
> +  const { releasePubkey, metadata, router, } = props
trailing comma

2022-10-17 21:18 UTC, ejf89 commented on js/web/components/Release.js
> +      getExchangeHistoryForRelease(releasePubkey)
release page is broken, may be related to this

2022-10-17 21:19 UTC, ejf89 commented on js/web/components/ReusableTable.js
> +const ReusableTableBody = ({ items, tableType, hasOverflow }) => {
+1

2022-10-17 21:21 UTC, ejf89 commented on js/web/components/Search.js
> +          <ResultsWrapper>
`ResultsWrapper` can be refactored and written once around this function

2022-10-17 21:21 UTC, ejf89 commented on js/web/components/SearchDropdown.js
> +    backgroundColor: 'rgba(255,255,255,0.8)',
transparency color values should be added to / pulled from the theme object

2022-10-17 21:22 UTC, ejf89 requested changes
almost there, needs some small tweaks

2022-10-18 14:25 UTC, facing-n commented
<img width="1074" alt="Screen Shot 2022-10-18 at 10 24 21 AM" src="https://user-images.githubusercontent.com/2960410/196458030-29b3ae2c-7978-4a32-8e66-8af2c985a8d8.png">

Releases in search Results should be `{Artist} - {Title}`, here they are just `{Title}`

2022-10-18 22:19 UTC, ejf89 commented on js/web/components/Hub.js
> +import Head from 'next/head'
`Head` and associated mark up should be in the associated files in `/pages`

2022-10-18 22:21 UTC, ejf89 commented on js/web/components/NavSearch.js
> +    console.log('NinaSdk.client', NinaSdk.client)
kill log

2022-10-18 22:24 UTC, ejf89 commented on js/web/components/Profile.js
> +      console.log('collected: ', collected)
kill log

2022-10-18 22:24 UTC, ejf89 commented on js/web/components/ReusableTable.js
> +        // ctas: data?.publicKey,
remove unused vars

2022-10-18 22:24 UTC, ejf89 commented on js/web/components/ReusableTable.js
> +        // ctas: data?.publicKey,
same as above

2022-10-20 17:38 UTC, ejf89 commented on js/web/components/Hub.js
> +    console.log('data', data)
log

2022-10-26 18:20 UTC, ejf89 approved these changes

2022-10-26 18:25 UTC, ejf89 reviewed
waiting for fix in search

2022-10-26 18:53 UTC, closed without merging