Hub create web
nina-protocol/nina pull request #815
Opened 2023-02-06 15:43 UTC by ikjudd

2023-02-13 19:08 UTC, ejf89 requested changes
this is looking good, just a couple comments/qs

2023-02-13 19:08 UTC, ejf89 commented on js/web/components/NavDrawer.js
> +                {`© ${new Date().getFullYear()} Nina Protocol Corp`}
+1

2023-02-13 19:35 UTC, ikjudd commented on js/sdk/src/components/HubCreate.js
> +                // value={imageProgress}
yes

2023-02-14 15:57 UTC, ejf89 approved these changes

2023-02-14 16:01 UTC, merged