Balance check upload
nina-protocol/nina pull request #835
Opened 2023-02-17 15:51 UTC by ikjudd

- Closes #834

2023-02-17 17:54 UTC, ejf89 commented on js/sdk/src/components/MediaDropzone.js
> +          <Box sx={{ padding: '35px 15px' }} disabled={true}>
?

2023-02-22 23:19 UTC, ejf89 approved these changes

2023-02-23 19:54 UTC, facing-n requested changes
1. the LowSolWarning component shouldn't be a modal.  it should be over the ReleaseCreateForm.  You shouldn't be able to manually dismiss the warning - instead the LowSolWarning should periodically call getUserBalances (every 5 seconds?) and dismiss warning when you have the right balance.

2. the required SOL amount is incorrect.  there is a diff cost if through a Hub - to err on the safe side we probably want to round up from NinaProgramActionCost.RELEASE_INIT_VIA_HUB, which should display as 0.023

2023-02-28 21:42 UTC, ejf89 commented on js/sdk/src/components/ReleaseCreate.js
> +  function roundUp(number, decimal) {
plz move this to `/Utils`

2023-02-28 21:43 UTC, ejf89 requested changes
plz move `roundUp` helper function to Utils

2023-02-28 22:05 UTC, ejf89 approved these changes

2023-03-03 19:34 UTC, facing-n approved these changes

2023-03-03 19:36 UTC, merged