Wallet connect fallback
nina-protocol/nina pull request #960
Opened 2023-04-20 21:59 UTC by ikjudd

- Closes #955

2023-04-20 22:25 UTC, ikjudd commented
**WEB**
- [ ] Wallet Modal displays when collecting a free Release
- [ ] Wallet Modal displays when purchasing a Release
- [ ] Wallet Modal displays when creating a Buy Offer
- [ ]  Wallet Modal displays when creating a Sell Offer
- [ ]  Wallet Modal displays when buying from Exchange
- [ ] Wallet Modal displays when attempting to Repost a Release

**HUBS**
- [ ] Wallet Modal displays when collecting a free Release
- [ ] Wallet Modal displays when purchasing a Release
- [ ] Wallet Modal displays when creating a Buy Offer
- [ ]  Wallet Modal displays when creating a Sell Offer
- [ ]  Wallet Modal displays when buying from Exchange
- [ ] Wallet Modal displays when attempting to Repost a Release

2023-04-21 15:55 UTC, ejf89 commented on js/sdk/src/index.js
> +export { default as IndentityVerification } from './components/IndentityVerification'
typo

2023-04-21 16:02 UTC, ejf89 commented on js/web/components/ReleaseCard.js
> +                sx={{ height: '22px', width: '22px' }}
why we changing this?

2023-04-21 16:02 UTC, ejf89 requested changes
plz fix type and cta placement in `releaseCard`

2023-04-25 17:12 UTC, merged